# Generated by Django 4.1.4 on 2023-01-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='curlocation',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='city',
            new_name='hostel',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='state',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pincode',
        ),
    ]
